### ISSUE TITLE
Red font should be a darker shade

### ISSUE THREAD

**Issue by ryangallen** [gregkaiser/Ryan-s-Site#1]
Use OSX's Digital Color Meter to identify the color of the red looking font, use that one.

Design Tip: Avoid 100% saturations of basic colors, especially for text. Examples:
- #F00 pure red
- #0F0 pure green
- #000 pure black
- #FFFF00 pure yellow (the worst)
  Instead, darken them up by adding more of the other spectrums, e.g. #C00 is much friendlier on the eye for red text, #222 is a dark gray that makes common text appear more sophisticated

**Comment by gregkaiser** [comment]
updated
