### ISSUE TITLE
Pretend client request: "The collections don't look right, can you do something to make them pop?"

### ISSUE THREAD

**Issue by ryangallen** [gregkaiser/Ryan-s-Site#4]
You'll get this a lot; A client or boss will give you an ambiguous request after they already approved the mockup. They're leaning on you to make a design decision on the fly.

Make your best judgement call and do something with the collections to "make them pop"
![screen shot 2015-06-18 at 2 41 10 pm](https://cloud.githubusercontent.com/assets/1379681/8239160/1bade50a-15c8-11e5-9011-5fe77e516809.png)

**Comment by gregkaiser** [comment]
Added a colored shadow for each of the images in collections
